"""Second migration

Revision ID: e188b7f3da11
Revises: fa84cc83d73a
Create Date: 2024-07-01 23:02:37.183336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e188b7f3da11'
down_revision: Union[str, None] = 'fa84cc83d73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usergroupassociation', sa.Column('rceive_newsletter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergroupassociation', 'rceive_newsletter')
    # ### end Alembic commands ###
