"""empty message

Revision ID: fc176e94fe05
Revises: 4f223b36625a
Create Date: 2025-02-02 22:33:16.490060

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fc176e94fe05'
down_revision: Union[str, None] = '4f223b36625a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('android_metadata')
    op.add_column('user', sa.Column('first_name_last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'first_name_last_name')
    op.create_table('android_metadata',
    sa.Column('locale', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
